name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Install tools
      run: |
        GO111MODULE=off go get golang.org/x/tools/cmd/goimports
    - name: Build & Test
      run: make build test verify-goimports
