name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.3
    - uses: actions/setup-go@v2.1.2
      with:
        go-version: '1.13'
    - name: Install goimports
      run: |
        GO111MODULE=off go get golang.org/x/tools/cmd/goimports
        echo "##[add-path]$(go env GOPATH)/bin"
    - name: Build & Test
      run: make build test verify-goimports
